apiVersion: v1
entries:
  mockforge:
  - apiVersion: v2
    appVersion: 0.3.62
    created: "2026-02-21T17:13:55.318453478Z"
    description: A Helm chart for MockForge - Advanced API mocking and chaos engineering
      platform
    digest: 8739c41e50dfbd0cf73d7be060f13fb61305a57ad0ee9cafb108303b57349b54
    home: https://mockforge.dev
    icon: https://mockforge.dev/logo.png
    keywords:
    - mockforge
    - api
    - mocking
    - chaos-engineering
    - testing
    maintainers:
    - email: team@mockforge.dev
      name: MockForge Team
    name: mockforge
    sources:
    - https://github.com/mockforge/mockforge
    type: application
    urls:
    - https://SaaSy-Solutions.github.io/mockforge/charts/mockforge-0.3.62.tgz
    version: 0.3.62
generated: "2026-02-21T17:13:55.317467667Z"
