apiVersion: v1
entries:
  mockforge:
  - apiVersion: v2
    appVersion: 0.3.70
    created: "2026-02-27T23:09:56.260857806Z"
    description: A Helm chart for MockForge - Advanced API mocking and chaos engineering
      platform
    digest: 92efa1d7db9f8e3d5cfa47480713539295ed2ced6368cf00175bb36ef30a998f
    home: https://mockforge.dev
    icon: https://mockforge.dev/logo.png
    keywords:
    - mockforge
    - api
    - mocking
    - chaos-engineering
    - testing
    maintainers:
    - email: team@mockforge.dev
      name: MockForge Team
    name: mockforge
    sources:
    - https://github.com/mockforge/mockforge
    type: application
    urls:
    - https://SaaSy-Solutions.github.io/mockforge/charts/mockforge-0.3.70.tgz
    version: 0.3.70
  - apiVersion: v2
    appVersion: 0.3.65
    created: "2026-02-27T23:09:56.259288689Z"
    description: A Helm chart for MockForge - Advanced API mocking and chaos engineering
      platform
    digest: 2c2219d3240583029daebfcf67e4a89252e6b2edb564db2ea0f2e93b6022943c
    home: https://mockforge.dev
    icon: https://mockforge.dev/logo.png
    keywords:
    - mockforge
    - api
    - mocking
    - chaos-engineering
    - testing
    maintainers:
    - email: team@mockforge.dev
      name: MockForge Team
    name: mockforge
    sources:
    - https://github.com/mockforge/mockforge
    type: application
    urls:
    - https://SaaSy-Solutions.github.io/mockforge/charts/mockforge-0.3.65.tgz
    version: 0.3.65
  - apiVersion: v2
    appVersion: 0.3.64
    created: "2026-02-27T23:09:56.257793901Z"
    description: A Helm chart for MockForge - Advanced API mocking and chaos engineering
      platform
    digest: 966abaa60d7c697c8833ba86d5dce0cadae2086d845105b042bc09115e97344f
    home: https://mockforge.dev
    icon: https://mockforge.dev/logo.png
    keywords:
    - mockforge
    - api
    - mocking
    - chaos-engineering
    - testing
    maintainers:
    - email: team@mockforge.dev
      name: MockForge Team
    name: mockforge
    sources:
    - https://github.com/mockforge/mockforge
    type: application
    urls:
    - https://SaaSy-Solutions.github.io/mockforge/charts/mockforge-0.3.64.tgz
    version: 0.3.64
  - apiVersion: v2
    appVersion: 0.3.63
    created: "2026-02-27T23:09:56.255896655Z"
    description: A Helm chart for MockForge - Advanced API mocking and chaos engineering
      platform
    digest: 251d46e38a3c2663c527dc1a1c90246d6ac51e9594ea77e7759094e660903d20
    home: https://mockforge.dev
    icon: https://mockforge.dev/logo.png
    keywords:
    - mockforge
    - api
    - mocking
    - chaos-engineering
    - testing
    maintainers:
    - email: team@mockforge.dev
      name: MockForge Team
    name: mockforge
    sources:
    - https://github.com/mockforge/mockforge
    type: application
    urls:
    - https://SaaSy-Solutions.github.io/mockforge/charts/mockforge-0.3.63.tgz
    version: 0.3.63
  - apiVersion: v2
    appVersion: 0.3.62
    created: "2026-02-27T23:09:56.255146976Z"
    description: A Helm chart for MockForge - Advanced API mocking and chaos engineering
      platform
    digest: 8739c41e50dfbd0cf73d7be060f13fb61305a57ad0ee9cafb108303b57349b54
    home: https://mockforge.dev
    icon: https://mockforge.dev/logo.png
    keywords:
    - mockforge
    - api
    - mocking
    - chaos-engineering
    - testing
    maintainers:
    - email: team@mockforge.dev
      name: MockForge Team
    name: mockforge
    sources:
    - https://github.com/mockforge/mockforge
    type: application
    urls:
    - https://SaaSy-Solutions.github.io/mockforge/charts/mockforge-0.3.62.tgz
    version: 0.3.62
generated: "2026-02-27T23:09:56.254195572Z"
