[package]
name = "mockforge-ui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Admin UI for MockForge - web-based interface for managing mock servers"
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
publish = true  # UI component used by mockforge-cli
include = [
    "src/**/*",
    "ui/dist/**/*",
    "build.rs",
    "build_ui.sh",
    "Cargo.toml",
    "README.md"
]

[dependencies]
axum = { workspace = true, features = ["macros"] }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-stream = { version = "0.1", features = ["time"] }
futures-util = "0.3"
tracing = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
mime_guess = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
reqwest = { workspace = true }
sysinfo = { workspace = true }
html-escape = "0.2"
once_cell = "1.19"
mockforge-core = { version = "0.2.7", path = "../mockforge-core" }
mockforge-http = { version = "0.2.7", path = "../mockforge-http", features = ["smtp", "mqtt"] }
mockforge-ws = { version = "0.2.7", path = "../mockforge-ws" }
mockforge-grpc = { version = "0.2.7", path = "../mockforge-grpc" }
mockforge-vbr = { version = "0.2.7", path = "../mockforge-vbr" }
mockforge-plugin-core = "0.2.7"
mockforge-plugin-loader = { version = "0.2.7", path = "../mockforge-plugin-loader" }
mockforge-analytics = { version = "0.2.7", path = "../mockforge-analytics" }

[build-dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
vergen = { version = "8.0", features = ["build", "git", "gitcl"] }

[dev-dependencies]
axum = { workspace = true, features = ["macros"] }
tokio = { workspace = true, features = ["rt", "macros"] }
# Need ServiceExt for oneshot
tower = { version = "0.5", features = ["util"] }
