[package]
name = "mockforge-ws"
version = "0.3.5"
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "WebSocket protocol support for MockForge"
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords = ["websocket", "ws", "api", "mock", "testing"]
categories = ["development-tools::testing", "web-programming::websocket"]

[lints.rust]
missing_docs = "deny"

[dependencies]
axum = { workspace = true }
tokio = { workspace = true }
futures = "0.3"
serde = { workspace = true }
serde_json = { workspace = true }
regex = { workspace = true }
jsonpath = "0.1"
tracing = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
fastrand = "2.0"
async-trait = { workspace = true }
thiserror = "2.0"
mockforge-core = "0.3.5"
mockforge-data = "0.3.5"
mockforge-observability = "0.3.5"
mockforge-tracing = "0.3.5"
opentelemetry = { version = "0.22", features = ["trace"] }

[dev-dependencies]
tokio = { version = "1.48", features = ["macros", "rt-multi-thread"] }
futures-util = "0.3"
tokio-tungstenite = { version = "0.28", features=["rustls-tls-native-roots"] }
axum = { version = "0.8" }
opentelemetry_sdk = "0.22"

[features]
default = []
data-faker = []
